from typing import Union, Any


class BaseField(object):
    TYPE = None
    DEFAULT = None

    def __init__(self, default=..., index=None): ...
    def value(self) -> str: ...

    def from_python(self, value) -> Union[bytes, int]: ...
    def to_python(self, value) -> Any: ...

    @classmethod
    def check_type(cls, other: 'BaseField') -> bool: ...
