from enum import IntEnum
from .integer_field import Int16Field


class IntEnumField(Int16Field):
    def __init__(self, int_enum: IntEnum, default=..., index=None): ...
    def from_python(self, value) -> int: ...
    def to_python(self, value) -> IntEnum: ...
