from typing import Union, Tuple

from .schema import Schema


class Document:
    def __init__(self, doc: Document, schema: Schema, readonly=False): ...
    def update(self, **kwargs): ...
    def __setitem__(self, key, value): ...
    def __getitem__(self, key) -> Union[int, str]: ...
    def __contains__(self, item) -> bool: ...
    def __iter__(self) -> Tuple[str, Union[int, str]]: ...
    def __repr__(self) -> str: ...

    @property
    def __dict__(self) -> dict: ...

