from threading import RLock
from typing import Dict, Union, Generator, Tuple, Any, Set, Iterable

from . import sophia
from .db import Database
from .schema import Schema


class Environment:
    _LOCKS = ...

    def __init__(self, path: str):
        self.path = ...         # type: str
        self.env = ...          # type: sophia.Environment
        self.databases = ...    # type: Set[Database]
        self._system_env = ...  # type: sophia.Environment
        self._system_db = ...   # type: sophia.Database

    def _compare_schema(self, db_name: str,
                        definition: Iterable[Tuple[str, str]]): ...
    def _create_env(self): ...
    def _create_system_env(self): ...
    def __setitem__(self, key, value): ...
    def open(self) -> bool: ...
    def __del__(self): ...
    def __getitem__(self, item: str) -> Union[str, int]: ...
    def __iter__(self): Generator[str, Union[int, str]]: ...
    def close(self, reopen: bool=True): ...
    def database(self, name: str, schema: Schema, **kwargs) -> Database: ...

    @property
    def _lock(self) -> RLock: ...

    @property
    def engine_config(self) -> Dict[str, Union[int, str]]: ...

    @property
    def is_closed(self) -> bool: ...

    @property
    def is_opened(self) -> bool: ...
